package group4.adminmng.model;

// ================================================================
// File    : OccupancyReport.java
// Package : com.heavenstay.model
// Desc    : Extends Report. Reads rooms.txt to calculate occupancy.
// ================================================================

import group4.adminmng.util.FileUtil;
import java.io.IOException;
import java.util.List;

public class OccupancyReport extends Report {

    private int    totalRooms;
    private int    occupiedRooms;
    private int    maintenanceRooms;
    private double occupancyRate;

    public OccupancyReport(String reportId, String generatedBy, String dateRange) {
        super(reportId, generatedBy, dateRange);
    }

    // ── Polymorphic gatherData ────────────────────────────────
    @Override
    public void gatherData() {
        try {
            List<String> lines = FileUtil.readAllLines("data/rooms.txt");
            totalRooms       = lines.size();
            occupiedRooms    = (int) lines.stream().filter(l -> l.contains("|Occupied|")).count();
            maintenanceRooms = (int) lines.stream().filter(l -> l.contains("|Maintenance|")).count();
            occupancyRate    = totalRooms > 0
                    ? (double) occupiedRooms / totalRooms * 100 : 0.0;
        } catch (IOException e) {
            totalRooms = occupiedRooms = maintenanceRooms = 0;
            occupancyRate = 0.0;
        }
    }

    // ── Polymorphic formatOutput ──────────────────────────────
    @Override
    public String formatOutput() {
        return "========================================\n"
                + "       HEAVEN STAY  –  OCCUPANCY REPORT\n"
                + "========================================\n"
                + "Report ID    : " + getReportId()      + "\n"
                + "Generated By : " + getGeneratedBy()   + "\n"
                + "Date Range   : " + getDateRange()     + "\n"
                + "Generated At : " + getGeneratedDate() + "\n"
                + "----------------------------------------\n"
                + "Total Rooms        : " + totalRooms       + "\n"
                + "Occupied Rooms     : " + occupiedRooms    + "\n"
                + "Maintenance Rooms  : " + maintenanceRooms + "\n"
                + "Available Rooms    : " + (totalRooms - occupiedRooms - maintenanceRooms) + "\n"
                + String.format("Occupancy Rate     : %.1f%%\n", occupancyRate)
                + "========================================\n";
    }

    // Getters
    public int    getTotalRooms()        { return totalRooms; }
    public int    getOccupiedRooms()     { return occupiedRooms; }
    public int    getMaintenanceRooms()  { return maintenanceRooms; }
    public double getOccupancyRate()     { return occupancyRate; }
}
