package group4.adminmng.model;

// ================================================================
// File    : RevenueReport.java
// Package : com.heavenstay.model
// Desc    : Extends Report. Reads payments.txt to calculate revenue.
// ================================================================

import group4.adminmng.util.FileUtil;
import java.io.IOException;
import java.util.List;
import java.util.logging.Logger;

public class RevenueReport extends Report {

    private static final Logger LOGGER = Logger.getLogger(RevenueReport.class.getName());

    private double totalRevenue;
    private int    totalBookings;
    private double averageStayValue;

    public RevenueReport(String reportId, String generatedBy, String dateRange) {
        super(reportId, generatedBy, dateRange);
    }

    // ── Polymorphic gatherData ────────────────────────────────
    @Override
    public void gatherData() {
        try {
            // payments.txt format: paymentId|bookingId|guestId|amount|method|status|date
            List<String> lines = FileUtil.readAllLines("data/payments.txt");
            totalRevenue  = 0.0;
            totalBookings = 0;
            for (String line : lines) {
                String[] p = line.split("\\|", -1);
                if (p.length >= 6 && "Completed".equalsIgnoreCase(p[5])) {
                    try {
                        totalRevenue += Double.parseDouble(p[3]);
                        totalBookings++;
                    } catch (NumberFormatException e) {
                        LOGGER.warning("Skipping invalid amount in payments.txt: " + p[3]);
                    }
                }
            }
            averageStayValue = totalBookings > 0 ? totalRevenue / totalBookings : 0.0;
        } catch (IOException e) {
            LOGGER.warning("Failed to read payments data: " + e.getMessage());
            totalRevenue = averageStayValue = 0.0;
            totalBookings = 0;
        }
    }

    // ── Polymorphic formatOutput ──────────────────────────────
    @Override
    public String formatOutput() {
        return "========================================\n"
                + "        HEAVEN STAY  –  REVENUE REPORT\n"
                + "========================================\n"
                + "Report ID      : " + getReportId()      + "\n"
                + "Generated By   : " + getGeneratedBy()   + "\n"
                + "Date Range     : " + getDateRange()     + "\n"
                + "Generated At   : " + getGeneratedDate() + "\n"
                + "----------------------------------------\n"
                + String.format("Total Revenue      : LKR %,.2f\n", totalRevenue)
                + "Total Bookings     : " + totalBookings + "\n"
                + String.format("Avg Stay Value     : LKR %,.2f\n", averageStayValue)
                + "========================================\n";
    }

    // Getters
    public double getTotalRevenue()      { return totalRevenue; }
    public int    getTotalBookings()     { return totalBookings; }
    public double getAverageStayValue()  { return averageStayValue; }
}
